name: Merge branch dev into rel-*
on:
  push:
    branches:
      - rel-*
jobs:
  auto-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{github.ref}}-auto-pr-${{github.runNumber}}
          token: ${{ github.token }}
