name: Merge rel-4.1 with main
on:
  push:
    branches:
      - rel-4.1
jobs:
  updateAuthors:
    runs-on: ubuntu-latest
    steps:
      uses: peter-evans/create-pull-request@v3
      with:
        reviewers: mehmet-erim
