name: Merge branch dev with rel-*
on:
  push:
    branches:
      - rel-*
jobs:
  auto-pr-sync-dev-with-rel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Reset promotion branch
        run: |
          git fetch origin $GITHUB_REF:$GITHUB_REF
          git pull origin rel-3.3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{github.ref}}-auto-pr-${{github.run_number}}
          title: Merge branch dev with ${{github.ref}}
          body: This PR generated automatically to merge dev with ${{github.ref}}.
          reviewers: ${{github.actor}}
          token: ${{ github.token }}
