name: Merge rel-4.1 with main
on:
  push:
    branches:
      - rel-4.1
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: 'update/'
          PULL_REQUEST_BRANCH: 'main'
          PULL_REQUEST_REVIEWERS: 'mehmet-erim'
