name: Merge branch dev into rel-*
on:
  push:
    branches:
      - rel-4.1
jobs:
  auto-pr-sync-dev-with-rel-*:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Reset promotion branch
        run: |
          git fetch origin rel-4.1:rel-4.1
          git reset --hard rel-4.1
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: production-promotion
