name: Sample job
on:
  push:
    branches:
      - dev
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, $GITLAB_USER_LOGIN!"
      - run: echo $GITHUB_RUN_ID $GITHUB_HEAD_REF
